name: TestingNoSse
on: [push]
jobs:
  compilation:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            friendly: clang
            compiler: clang++
            aptpkg: clang
          - os: ubuntu-22.04
            friendly: gcc
            compiler: g++
            aptpkg: build-essential
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: FlashMQTests
    name: "${{ matrix.friendly }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update
      # Build prerequisites
      - run: sudo apt install -y cmake libssl-dev libcurl4-openssl-dev ${{ matrix.aptpkg }}
      # Building
      - run: ./run-make-from-ci.sh --compiler "${{ matrix.compiler }}" --extra-config "FMQ_NO_SSE=1"
      - run: ./run-tests-from-ci.sh
